# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: opensuspect

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd src
          godot -v --export "Client" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Windows Desktop Build
        run: |
          mkdir -v -p build/windows-desktop
          cd src
          godot -v --export "Windows Desktop" ../build/windows-desktop/$EXPORT_NAME.exe
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-desktop
          path: build/windows-desktop
